src/components/common/Footer.tsx
src/components/common/Header.tsx
src/index.css

#2 
components > common > Footer.tsx
components > common > Header.tsx

[Feature] Footer 생성, Header design 수정

---

src/types/todo.ts

[Feature] todo 타입 정의

---

src/components/panels/TodoPanel.tsx

TodoPanel.tsx에 타이틀 추가
- Todo-List 타이틀 추가

[Feature] Todo-List 타이틀 추가

---

src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/todo/TodoList.tsx

링크, 수정/삭제 기능 추가
- TodoInput.tsx에 입력 창 두 개로 분리(todo, link)
- TodoItem.tsx에 개별 투두 항목 코드 생성
- TodoList.tsx에 투두 목록 전체 뿌려주기 기능 추가

[Feature] todo 링크, 수정/삭제 기능 추가

---

src/store/todo.ts

[Feature] todo 상태 관리 추가

---

src/index.css
tailwind.config.js

폰트 설정 추가
- tailwind.config.js
- index.css

[Feature] tailwind font 설정 추가

---

package-lock.json
package.json
src/components/panels/UserPanel.tsx
src/components/user/UserCalendar.tsx

#17 
- 캘린더 라이브러리 사용해서 작성
- 기본 디자인 작성완료
- 더미 데이터 넣고 색상 넣기 테스트 완료

[Feature] 캘린더 기본구조

---

src/components/user/UserCalendar.tsx

#22 
- 임시 데이터를 사용해 월별 잔디심기 구현
- 클릭 시 해당 일자 secondary-color로 테두리 (추후 tailwind 컬러로 변경 필요), 마우스 호버 css 변경
- 일자 클릭 시 해당 일자 값으로 가지고 있도록 구현 (백엔드 통신 시 필요)

[Feature] 캘린더 이벤트 처리 (초기구현)

---

package-lock.json
src/components/panels/TodoPanel.tsx
src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/todo/TodoList.tsx
src/pages/HomePage.tsx

#24 
- 데스크탑 컨텐츠 너비 360px 고정
- 각 패널들 인접하는 부분 패딩 70px로 맞추기

[Feature] 데스크탑 레이아웃

---

src/api/axios.ts
src/components/user/UserCalendar.tsx
tsconfig.json

axios.ts 만들어서 연결 처리
#22 
- axios 로컬 데이터 처리 (카카오 로그인 시 받아온 accessToken 가져와서)
> 추후 세션 스토리지에 accessToken없을 경우 처리 추가하기
- 받아온 내용 화면 랜더링 3번 이슈로 인해 캘린더에 뿌리기 x

[Feature] 캘린더 axios 통신 연결(로컬)

---

src/App.tsx
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/common/Wrapper.ts
src/components/common/types.ts
src/hooks/useModal.ts
src/pages/home.tsx
src/styles/globals.css

#20
- Footer 생성 
- Wrapper.tsx에 Postion 추가

[Feature] Footer 생성 및 Position 지정

---

src/components/panels/TodoPanel.tsx
src/components/timer/SetTimer.tsx
src/components/user/UserCalendar.tsx
src/hooks/useViewport.ts
src/pages/HomePage.tsx
src/router/index.tsx

#30 
- 한번씩만 랜더링 되도록 homepage.tsx 변경한 것 패널 별 주석 추가

[Fix] 각 패널별 랜더링 주석 추가

---

package-lock.json
package.json
src/components/common/Header.tsx
vite.config.ts

#20
- Header 내 로고 이미지가 엔박 나는 문제 해결

[Fix] 이미지 엔박 문제 해결

---

src/App.tsx
src/components/common/Header.tsx
src/features/auth/useAuth.ts
src/main.tsx

#2 
로그인, 로그아웃 api 연동
헤더 로그아웃버튼 조건부 렌더링 구현

[Feature] 로그인, 로그아웃 API 연동 

---

src/components/todo/TodoItem.tsx

#5 
- todo.link에 외부 링크 참조 보정 로직 추가

[Fix] 링크가 포함된 todoItem에 "https://" 보정 로직 수정

---

src/pages/landing.tsx

#11 
- desktop, tablet, phone 반응형 추가

[Feature] 랜딩페이지 반응형 구현

---

index.html
src/components/common/DropdownPortal.tsx
src/components/todo/TodoItem.tsx

#5 
- components/common 에 DropdownPortal.tsx 만들어서 수정/삭제 모달 처리
- 그에 따른 TodoItem.tsx 수정
- index.html 에 portal div 추가

[Feat] 수정/삭제 모달 위치 수정

---

src/components/panels/UserPanel.tsx
src/components/user/UserGreeting.tsx

#52 
- UserPane.tsx
- UserGreeting.tsx
- figma에 맞게 화면 구현

[Feature] UserPanel UI

---

src/components/todo/TodoItem.tsx

#45 
- TodoItem에 투두 텍스트 수정만 됐었던 것을 링크까지 수정 가능하도록 코드 추가.

[Feature] todo 텍스트, 링크 수정 기능 완료

---

src/components/friend/FriendList.tsx
src/features/friend/FriendService.ts
src/store/friend.ts

#39 
src/components/friend/FriendList.tsx
src/features/friend/FriendService.ts
src/store/friend.ts

[Feature] 친구 목록 조회 API 연동, 친구 리스트 렌더링

---

src/components/layout/MainLayout.tsx
src/pages/HomePage.tsx

#24 
- homepage.tsx에서 태블릿, 모바일 -> 스크롤 기능 추가 (개발 편의성을  위해)
- mainlayout 에서 footer와 mainlayout 내용 분리되도록 코드 수정

[Feature] mainlayout, homepage 수정 - 스크롤 기능 추가

---

src/components/modals/FriendAddModal.tsx
src/components/modals/FriendRequestModal.tsx

[Fix] modal UI 수정

---

src/components/timer/SetTimer.tsx

[Feature] Set Timer UI & 기능 구현

---

src/components/home/CalendarBox.tsx

#36
- 사용하지 않는 값을 써서 배포되지 않는 문제를 _ 로 변경해 해결

[Fix] 배포문제 해결

---

src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/user/UserCalendar.tsx
src/store/calendar.ts

#63 
- 투두 추가/삭제/체크여부에 따라 캘린더 새로고침 반영 (달성률 실시간 반영)

[Feature] todo 추가/삭제/체크 여부에 따라 캘린더 달성률 반영

---

src/components/panels/TodoPanel.tsx
src/components/todo/TodoInput.tsx
src/components/user/UserCalendar.tsx
src/utils/date.ts

#63 
- 투두 추가 시 캘린더에서 받아온 날짜에 등록하도록 변경
- UserCalendar.tsx :  한국 시간대 변경 코드 calendar.ts에 트리거로 추가 후 import 하게 변경
- TodoPanel.tsx : 캘린더에서 받은 seletedDate를 전달하도록 변경

[Fix] Todo input 시 캘린더 선택 날짜 받아와서 등록

---

src/components/user/UserGreeting.tsx
src/store/auth.ts

[Feature] 유저 정보를 로그인한 유저 정보로 반영

---

package-lock.json
package.json
src/components/home/CalendarBox.tsx
src/components/home/TimerBox.tsx
src/pages/home.tsx

#54
- 타이머 - 숫자 버전
- 타이머 - 이미지 버전
- 2개의 타이머 flex로 묶음

[Feature] 타이머 UI 완료

---

src/components/timer/SetTimer.tsx

#61 
- 시간 자동 포멧팅: 1:00 => 01:00
- 시간 입력 시 1000분 미만으로 설정되도록 수정

[Feature] 시간 자동 포멧팅, 시간 1000분 미만으로 설정되도록 조정

---

src/types/auth.ts

[Fix] auth type 수정

---

src/App.tsx
src/components/common/CustomTimerToast.tsx
src/components/timer/SetTimer.tsx

[Feature] Timer Toast 작업

---

src/components/timer/SetTimer.tsx

#61 
- timer의 autoClose 조정 
- play icon 크기 조정

[Feature] timer duration, icon 크기 조정

---

src/components/todo/TodoTemplate.tsx

#40 
- 배포 에러 해결 _ 사용하지 않는 함수 호출

[Fix] 배포 에러 해결

---

src/components/home/FriendBox.tsx
src/components/home/FriendItem.tsx

#78
- 친구 리스트가 없을 때, UI 구현 - '친구가 없습니다!' 문구

[Feature] 친구 리스트가 없을 때 UI 

---

src/components/panels/TodoPanel.tsx
src/components/todo/TodoInput.tsx

#5 
- add 버튼 호버 색상 변경
- 글씨 크기 조정
- 스크롤 범위 수정

[Feature] add 버튼 호버, todoItem 스크롤 범위 조정

---

src/pages/HomePage.tsx
src/router/index.tsx

#1 
- 메인화면 반응형 범위 변경
- index.ts 불필요한 useMemo 삭제

[Feature] 메인화면 반응형 범위 변경

---

src/components/friend/FriendList.tsx
src/hooks/useViewport.ts
src/pages/HomePage.tsx
src/pages/LandingPage.tsx
tailwind.config.js

#60 
src/components/friend/FriendList.tsx
src/hooks/useViewport.ts
src/pages/HomePage.tsx
src/pages/LandingPage.tsx
tailwind.config.js

[Feature] 반응형 UI 수정 

---

.gitignore
package-lock.json
package.json
src/App.tsx
src/apis/client.ts
src/apis/home.ts
src/components/common/Header.tsx
src/components/home/GreetingBox.tsx
src/main.tsx
src/pages/home.tsx
src/pages/landing.tsx
src/pages/loginSuccess.tsx
src/store/user.ts
src/store/userStore.ts
src/types/home.ts

#94
- .env 와 client.ts로 API 기본 세팅
- 로그인, 로그아웃 API 연결 - zustand와 zustand-cookie-storage로 token 관리
- home에서 user-info 가져오는 API 연결 후, 해당 API 연결 실패 시, landing으로 넘어가도록 설정
현재, 로그인 상태 아닐 시, 메인에서 landing으로 넘어가는 과정이 너무 느리다는 문제 있음. 이후 수정 필요.

[Feature] 로그인/로그아웃 API 연결

---

src/apis/home.ts
src/apis/todo.ts
src/components/home/CalendarBox.tsx
src/components/todo/TodoTemplate.tsx
src/store/dateStore.ts
src/styles/home/calendarBox.css
src/types/home.ts
src/types/todo.ts

#99
- calendar API 연결 후, 각 날짜에 따른 opacity 부여
- calendar의 각 날짜 누를 시, 해당 날짜를 전역관리함
- todoList API에 해당 날짜를 넣어 todoList 가져옴

[Feature] calendar관련 API 연결

---

src/components/home/CalendarBox.tsx
src/components/home/FriendBox.tsx
src/components/home/GreetingBox.tsx
src/components/modals/FriendRequestsModal.tsx
src/components/modals/ModalTemplate.tsx
src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/todo/TodoTemplate.tsx
src/pages/friend-home.tsx
src/pages/home.tsx
src/store/todoStore.ts
src/types/todo.ts

#102
- Friend Modal 버튼 연결
- phone일 시, 열리는 TodoList 박스 스타일 수정
- tablet일 시, calendar 크기 지정

[Feature] 모달 연결 및 스타일 수정

---

src/components/panels/UserPanel.tsx
src/pages/HomePage.tsx
src/router/index.tsx

#2 
src/components/panels/UserPanel.tsx
src/pages/HomePage.tsx

[Fix] 반응형 UI 수정

---

src/apis/todo.ts
src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/todo/TodoTemplate.tsx

#105 
- addTodo 연결
- toggleCheck 연결
- editTodo 연결
- deleteTodo 연결

[Feature] Todo API 연결

---

src/components/user/UserCalendar.tsx

#22 
- 코드 사이드 이펙트 관리
- 에러 안전성 확보

[Refactor] 캘린더 코드 사이드 이펙트 관리, 에러 안전성 확보

---

src/components/modals/FriendAddModal.tsx
src/components/modals/FriendRequestModal.tsx
src/components/panels/RightPanel.tsx
src/pages/HomePage.tsx

#39 
src/components/modals/FriendAddModal.tsx
src/components/modals/FriendRequestModal.tsx
src/components/panels/RightPanel.tsx
src/pages/HomePage.tsx

[Fix] modal 창 렌더링 오류 해결

---

src/App.tsx
src/apis/modal.ts
src/components/common/toast/ConfirmFailToast.tsx
src/components/modals/FriendAddModal.tsx
src/components/modals/FriendRequestsModal.tsx

#108 
- Friend 요청 리스트 get
- Friend 요청 승인/거절 post
- Friend 요청 보내기 post

[Feature] Friend 모달 API 연결

---

src/App.tsx

#94
-  login direct 되는 path 수정

[Fix] login path 수정

---

src/App.tsx
src/components/home/FriendBox.tsx

#76 
- friendRequest 상태에 따라 색 변경

[Feature] friendRequest 상태에 따라 색 변경

---

src/components/panels/UserPanel.tsx

#52 
- align-items: flex-center -> flex-start로 변경

[Fix] userpanel 정렬 변경

---

src/components/friend/FriendList.tsx
src/components/friend/FriendTodoPanel.tsx
src/components/friend/FriendUserPanel.tsx
src/components/timer/SetTimer.tsx
src/components/todo/TodoInput.tsx
src/components/todo/TodoItem.tsx
src/components/todo/TodoList.tsx
src/components/user/UserCalendar.tsx
src/components/user/UserGreeting.tsx
src/pages/FriendPage.tsx
src/router/index.tsx
src/types/todo.ts

#106 
- FriendPage 반응형 구현 완료
- Tooltip 메시지 구현 (접근 불가)
- 기능 구현 완료

[Feature] FriendPage 기능 & UI 완료

---

src/components/panels/UserPanel.tsx
src/pages/HomePage.tsx

[Fix] 레이아웃 수정

---

src/components/user/UserCalendar.tsx

[Fix] 캘린더 크기 조정

---

src/components/common/Header.tsx
src/pages/HomePage.tsx

#2 
src/components/common/Header.tsx
src/pages/HomePage.tsx

[Feature] 헤더 기능 추가, main layout 수정 

---

src/components/common/CustomErrorToast.tsx
src/components/common/CustomSuccessToast.tsx
src/components/modals/FriendAddModal.tsx
src/components/user/UserCalendar.tsx

#39 
src/components/common/CustomErrorToast.tsx
src/components/common/CustomSuccessToast.tsx
src/components/modals/FriendAddModal.tsx

[Fix] 이메일 중복검사 서버에서 처리

---

src/components/modals/FriendAddModal.tsx

#39 
src/components/modals/FriendAddModal.tsx

[FIx] email입력 onchange 함수 추가

---

src/hooks/useModal.ts
src/pages/home.tsx

#76 
- Friend 요청 전부 처리 후 다시 홈 들어갔을 때 아이콘 색상 변경되도록 수정
- 모달 닫으면 FriendBox 리렌더링 되도록함

[Feature] Friend 아이콘 색상 변경 반영

---

src/components/common/toast/ConfirmFailToast.tsx
src/components/common/toast/ConfirmSuccessToast.tsx
src/components/modals/FriendAddModal.tsx

[Feature] toast message 수정

---

src/components/common/toast/ConfirmFailToast.tsx
src/components/common/toast/ConfirmSuccessToast.tsx
src/components/modals/FriendAddModal.tsx

[Feat] toast message 수정

---

src/components/modals/FriendAddModal.tsx

[Feat] toast message 스타일링 수정

---

src/components/modals/FriendAddModal.tsx

[Feature] toast message 스타일링 수정

---

src/components/modals/FriendRequestsModal.tsx

#76 
- friendRequest scrollbar-hide 설정

[Style] friendRequest scrollbar-hide 설정
